[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    
    # Updated CSP
    Content-Security-Policy = """
      default-src 'self';
      base-uri 'self';
      script-src 'self' 'wasm-unsafe-eval';
      worker-src 'self' blob:;
      connect-src 'self' 
        https://huggingface.co 
        https://cdn-lfs.huggingface.co 
        https://*.huggingface.co 
        https://*.xethub.hf.co 
        https://raw.githubusercontent.com 
        https://*.githubusercontent.com;
      img-src 'self' data: blob:;
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
      form-action 'none';
      object-src 'none';
      media-src 'self';
      manifest-src 'self';
      upgrade-insecure-requests;
      block-all-mixed-content;
    """
    
    # Cache Control
    Cache-Control = "no-cache, no-store, must-revalidate, private, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Surrogate-Control = "no-store"
